publish_frequency: 2.0
transform_tolerance: 0.5

footprint: [[0.35, 0.28], [-0.35, 0.28], [-0.35, -0.28], [0.35, -0.28]]

inflation_layer:
  inflation_radius: 0.1
  cost_scaling_factor: 0.2
  transform_tolerance: 0.5

obstacle_layer:
  obstacle_range: 3.5
  raytrace_range: 5.5
  transform_tolerance: 0.5
  observation_sources: front_laser
  front_laser:
    sensor_frame: robot_front_laser_link
    data_type: LaserScan
    topic: front_laser/filtered_scan
    marking: true
    clearing: true
    observation_persistence: 0.0

rgbd_laserscan_obstacle_layer:
  obstacle_range: 3.5
  raytrace_range: 5.5
  transform_tolerance: 0.5
  observation_sources: front_rgbd
  front_rgbd:
    sensor_frame: robot_front_rgbd_camera_link
    data_type: LaserScan
    topic: front_rgbd_camera/point_cloud_scan_filtered
    marking: true
    clearing: true
    observation_persistence: 0.0
