global_costmap:
  global_frame: /robot_map
  robot_base_frame: /robot_base_footprint
  update_frequency: 2.0
  static_map: true
  width: 200.0
  height: 200.0
  # robot radius +safety_delta 0.25 + 0.02
  # set to permit drawing a trajectory through the narrowest door
  robot_radius: 0.0

  inflation_layer:
    inflation_radius: 0.35
    cost_scaling_factor: 20
    transform_tolerance: 0.5

  plugins:
    -
      name: static_map
      type: "costmap_2d::StaticLayer"
    -
      name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    -
      name: rgbd_laserscan_obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    -
      name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_map:
      lethal_cost_threshold: 70
      static_map: true
      track_unknown_space: false
      unknown_cost_value: 1
      trinary_costmap: false
      use_maximum: true
