type: robot_local_control_components/NavigationComponent
desired_freq: 1.0

check_sensors_state: true
check_localization_state: true
has_safety_laser: false
safety_laser_mode_allowed: safe
charge_disable_procedures: true
uncharge_procedure_name: UnchargeComponent

components:
 - GoToComponent
 - MoveComponent
 - ChargeComponent
 - UnchargeComponent

GoToComponent:
  type: robot_local_control_procedures/GoToMoveBase
  desired_freq: 5.0
  action_namespace: move_base
  global_frame: robot_map
  base_frame: robot_base_footprint
  default_yaw_tolerance: 0.05 # when goal has orientation. if orientation is invalid, goal tolerance is changed to 3.14
  has_safety_laser: false
  yaw_tolerance: 0.0175
  xy_tolerance: 0.05
  preemptable: false
  clear_costmaps_before_send_goal: false
  local_planner_namespace: TebLocalPlannerROS

MoveComponent:
  type: robot_local_control_procedures/Move
  desired_freq: 5.0
  action_namespace: move

ChargeComponent:
  type: robot_local_control_procedures/Charge
  desired_freq: 5.0
  has_laser_safety: false # determines if the robot has safety_lasers and the safety zone must be changed
  docker_namespace: pp_docker
  dock_frame: robot_docking_station_laser
  generic_dock_frame: robot_docking_station_([0-9]+)
  laser_mode_at_begining: docking_station
  robot_dock_frame: robot_base_footprint
  dock_offset_x: -0.45 # 0.31 robot base to contacts + 0.14 docking station reflector to contacts
  move_namespace: move
  step_in_distance: 0.0 # Indicates the distance that the robot is going to move in x-axis after the docking. If 0.0 then no move action is done
  set_laser_to_standby: false # If 'true' then the lasers will be in standby after the docking
  move:
    max_velocity:
      linear_x: 0.015
      linear_y: 0.015
      angular_z: 0.1
  dock:
    max_velocity:
      linear_x: 0.1
      linear_y: 0.1
      angular_z: 0.1

UnchargeComponent:
  type: robot_local_control_procedures/Uncharge
  desired_freq: 5.0
  has_laser_safety: false # determines if the robot has safety_lasers and the safety zone must be changed
  move_namespace: move
  laser_mode_at_finish: standard
  step_back_distance: 0.5 # Indicates the distance that the robot is going to move backwards. If 0.0 then no rotation action is done
  rotation: 3.14 # Indicates the rotation that the robot is going to move after moving backwards. If 0.0 then no rotation action is done
  move:
    max_velocity:
      linear_x: 0.05
      linear_y: 0.0
      angular_z: 0.15
